version: '2'
services:
  laravel:
    container_name: laravel_server
    build: server/.
    ports:
      - 81:80
    volumes:
     - ../app:/var/www/
     - ./server/nginx/conf.d:/etc/nginx/conf.d/
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3307
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
     # - MONGO_HOST=mongodb
     # - MONGO_PORT=27018
     # - MONGO_USERNAME=laravel
     # - MONGO_PASSWORD=laravel
    depends_on:
      - mariadb
    networks:
      - laravel-bridge
#  mongodb:
#    image: bitnami/mongodb:latest
#    ports:
#    - "27018:27017"
#    environment:
#    - MONGODB_USERNAME=laravel
#    - MONGODB_PASSWORD=laravel
#    - MONGODB_DATABASE=instagram
#    - MONGODB_ROOT_PASSWORD=root
#    networks:
#      - laravel-bridge
  mariadb:
    image: mariadb:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
    networks:
      - laravel-bridge
networks:
 laravel-bridge:
   driver: bridge
